### ISSUE TITLE
Reader view text-to-speech option

### ISSUE THREAD

**Issue by simevidas** [SpitFire-666/Firefox-Stuff#1]
Firefox’s reader view has an option to speak the text of the article. I think this feature deserves its own entry in your list.

<img width="772" alt="Screenshot 2022-10-12 at 19 11 13" src="https://user-images.githubusercontent.com/716405/195406034-2a82428b-c9ec-4e5d-a7e6-3565427b333f.png">

**Comment by SpitFire-666** [comment]
Thanks for the feedback! I just checked and Edge has this too, however Chrome doesn't. So that's worth noting and I've updated the page!
