### ISSUE TITLE
Important features missing in firefox

### ISSUE THREAD

**Issue by alfredonodo** [SpitFire-666/Firefox-Stuff#2]
Hello,
if you are objective, you should add very important features that are not available in firefox:

- [PWA](https://connect.mozilla.org/t5/ideas/bring-back-pwa-progressive-web-apps/idi-p/35)
- WebRTC:[ tab audio sharing](https://bugzilla.mozilla.org/show_bug.cgi?id=1541425) and [facetime](https://bugzilla.mozilla.org/show_bug.cgi?id=1716090)
- [WebRTC E2EE](https://bugzilla.mozilla.org/show_bug.cgi?id=1631263)
- [Fission](https://wiki.mozilla.org/Project_Fission): android only
- [JPEG XL](https://bugzilla.mozilla.org/show_bug.cgi?id=1539075)
- [WebGPU](https://bugzilla.mozilla.org/show_bug.cgi?id=1602129)
- [Native tab grouping](https://connect.mozilla.org/t5/ideas/native-tab-grouping-more-customizable-tab-bar/idi-p/303)
- [Site specific extensions](https://connect.mozilla.org/t5/ideas/option-to-allow-extensions-to-run-only-on-specific-websites/idi-p/146)
- [Built-in translator](https://connect.mozilla.org/t5/ideas/get-built-in-translation-feature/idi-p/5347)
- [Built-in dark mode](https://connect.mozilla.org/t5/ideas/built-in-dark-mode-for-web-contents/idi-p/283)
- [Built-in auto tab discard](https://connect.mozilla.org/t5/ideas/firefox-should-suspend-tabs-to-better-performance/idi-p/6255)
- [Multi profiles support](https://connect.mozilla.org/t5/ideas/shortcut-for-different-profiles/idi-p/707)
- [Built-in ads blocker](https://bugzilla.mozilla.org/show_bug.cgi?id=1638808): [privacy features](https://privacytests.org/)
- [Support CTAP2 (FIDO2)](https://bugzilla.mozilla.org/show_bug.cgi?id=1530370)
- [Speech Recognition API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#browser_compatibility) and [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1481194)
- [Multi Account-Containers](https://github.com/mozilla/multi-account-containers/issues/1929): android only
- [Service Workers](https://bugzilla.mozilla.org/show_bug.cgi?id=ServiceWorkers)

**Comment by SpitFire-666** [comment]
Thanks for the feedback! I'd been thinking about this aspect, and it's partly addressed by the Feature Requests section (which also includes some high profile bugs).

Leave it with me 😉

**Comment by alfredonodo** [comment]
Well. This feature request does not exist https://connect.mozilla.org/t5/ideas/add-a-quot-reveal-password-quot-function-for-logins/idi-p/1140

**Comment by NSQY** [comment]
Technically, Firefox does have the ability to use multiple profiles, but it is hidden under ``about:profiles``. To achieve similar functionality to Chromium you need an extension that also requires the installation of additional software. https://addons.mozilla.org/en-US/firefox/addon/profile-switcher/ 

There are also limitations with profiles, for instance you are unable to close any open profile if one of them is currently downloading something. In general, the feature is very poorly implemented.

**Comment by SpitFire-666** [comment]
> Well. This feature request does not exist https://connect.mozilla.org/t5/ideas/add-a-quot-reveal-password-quot-function-for-logins/idi-p/1140

@alfredonodo hey thanks, I just checked - only I can see it. I think it must be stuck in limbo. I've updated it now.

**Comment by SpitFire-666** [comment]
@alfredonodo updated the page with all the features you mentioned in your original post.

Since it's been a while, any others I should add?

**Comment by alfredonodo** [comment]
Hi,
I don't see anything else at the moment. You can close the issue, I will get back to you if I find something missing.
Thank you
