### ISSUE TITLE
Replace Imagus with Hoverzoom+ or Imagus Mod

### ISSUE THREAD

**Issue by KAGEYAM4** [SpitFire-666/Firefox-Stuff#8]
The original Imagus is not opensource and not maintained. Found these alternative opensource projects - >

https://github.com/TheFantasticWarrior/chrome-extension-imagus
https://github.com/extesy/hoverzoom/

**Comment by SpitFire-666** [comment]
Cheers, done - I included imagus-mod  since I've been using it myself 👍
